export const ENDPOINTS = {
  season:              '/seasons',
  seasonById:          (id: string) => `/seasons/${id}`,
  style:               '/styles',
  styleById:           (id: string) => `/styles/${id}`,
  article:             '/articles',
  articleById:         (id: string) => `/articles/${id}`,
  articlesByStyle:     (styleId: string) => `/styles/${styleId}/articles`,
  bom:                 '/boms',
  bomById:             (id: string) => `/boms/${id}`,
  bomsByArticle:       (articleId: string) => `/articles/${articleId}/boms`,
  item:                '/items',
  itemById:            (id: string) => `/items/${id}`,
  fabric:              '/fabrics',
  fabricById:          (id: string) => `/fabrics/${id}`,
  material:            '/materials',
  materialById:        (id: string) => `/materials/${id}`,
  materialTexture:     '/material-textures',
  materialTextureByMaterial: (materialId: string) => `/materials/${materialId}/textures`,
  trim:                '/trims',
  trimById:            (id: string) => `/trims/${id}`,
  button:              '/buttons',
  buttonById:          (id: string) => `/buttons/${id}`,
  buttonHole:          '/button-holes',
  buttonHoleById:      (id: string) => `/button-holes/${id}`,
  zipper:              '/zippers',
  zipperById:          (id: string) => `/zippers/${id}`,
  graphic:             '/graphics',
  graphicById:         (id: string) => `/graphics/${id}`,
  topStitch:           '/top-stitches',
  topStitchById:       (id: string) => `/top-stitches/${id}`,
  physicalPropertyType:     '/physical-property-types',
  physicalPropertyTypeById: (id: string) => `/physical-property-types/${id}`,
} as const
